spring:
  cloud:
    gateway:
      routes:
        - id: api-route1
          uri: http://127.0.0.1:8011  # ?????????????????????/????????host???? localhost:8090
          predicates:
            - Path=/api-m/**,/test/{segment}